/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HO2;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        
        Student s1 = new Student("Mickey", "Mouse", 1, 2);
        Student s2 = new Student("Donald", "Duck", 2, 6);
        Student s3 = new Student("Roger", "Boom", 4, 1);

        Stackable<Student> stack = new Stack<Student>();

        stack.push(s1);
        stack.push(s2);
        stack.push(s3);
        stack.printAll();
        
        System.out.println("before pop:");
        printStack(stack);

        Student stud = stack.pop();

        System.out.println("before clear");
        printStack(stack);

        stack.clear();
        printStack(stack);
    }

    private static void printStack (Stackable<Student> stack) { 
        System.out.println("-------------------------------------");
        System.out.println("Peek: " + stack.peek());
        System.out.println("Size: " + stack.size());
        System.out.println("Empty: " + stack.isEmpty());
    }
}
